development:
  adapter: postgresql
  encoding: unicode
  database: stl_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: stl_test
  username: postgres
  password: postgres
  host: localhost
